Contact form Added (html and css)
gersonhiggins/Portfolio_Web pull request #2
Opened 2023-03-28 22:48 UTC by gersonhiggins

Add Html form
Add Css styles for Contact form
Linters checkout

2023-03-28 23:01 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @gersonhiggins 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-28 23:01 UTC, MaganaAsiati commented on index.html
> +<input type="text" name="name" id="name" required placeholder="   Lorem Ipsum">
- Kindly make sure as required in the project,  name input (can be first name and last name field depending on the template used) has maxlength="30" attribute. so please also add maxlength in the properties of your input :+1:

2023-03-28 23:01 UTC, MaganaAsiati commented on index.html
> +                <textarea name="" required placeholder="  Write your message here...."></textarea>
- Kindly make sure as required in the project,  Message input has `maxlength="500"` attribute. so please also add maxlength in the properties of your input :+1:

2023-03-28 23:12 UTC, topeogunleye approved these changes
### Hi @gersonhiggins, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Added max length required attribute ✔️ 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 16:02 UTC, closed without merging

2023-03-30 01:09 UTC, abiy006 commented
Hi @gersonhiggins - Nice to see you get approved this section. Well deserve !!

2023-03-30 01:32 UTC, gersonhiggins commented
@abiy006 thanks man